# Generated by Django 5.2.1 on 2025-12-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='📚', help_text='Emoji or Icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='4 Weeks', help_text="e.g. '4 Weeks', '10 Hours'", max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(default='https://via.placeholder.com/300', help_text='URL to course image', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.category'),
        ),
    ]
