# Generated by Django 5.2.1 on 2025-12-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_course_students_alter_course_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certification',
            field=models.TextField(blank=True, help_text='List your certifications', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, help_text='Describe your education', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, help_text='Describe your work experience', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='List your skills (one per line)', null=True),
        ),
    ]
