# Generated by Django 5.2.1 on 2025-12-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_certification_user_education_user_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, help_text='URL to your public LinkedIn Profile', null=True),
        ),
    ]
